services:
  timescaledb:
    ports:
      - "5432:5432"
  beacon:
    build:
      context: .
      target: dev
    ports:
      - "4000:4000"
    volumes:
      - .:/build
  migrate:
    build:
      context: .
      target: dev
    command: ["go", "run", ".", "-migrate", "-dev"]
  dashboard:
    build:
      context: ./dashboard
    ports:
      - "3000:3000"
    env_file:
      - path: ./dashboard/.env
        required: false
