on:
  push:
    tags:
      - "v*"
name: Build & Deploy
jobs:
  build:
    name: Push branches and PRs
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.fork && !github.event.pull_request.head.repo.fork && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == 'amir20/drain') }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: amir20/drain
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    name: Deploy to server
    steps:
      - uses: actions/checkout@v4
      - uses: arwynfr/actions-docker-context@v2
        with:
          docker_host: ssh://root@b.dozzle.dev
          context_name: "beacon"
          ssh_cert: ${{ secrets.SSH_CERT }}
          ssh_key: ${{ secrets.SSH_KEY }}
      - run: docker --context beacon stack deploy -c docker-compose.yml -c docker-compose.prod.yml data
